name: build image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

env:
  SOPS_VERSION: 3.8.1
  VALS_VERSION: 0.37.0
  HELM_SECRETS_VERSION: 4.6.0
  HELMFILE_VERSION: 0.163.1
  HELM_GIT_VERSION: 0.15.1
  KUBECTL_VERSION: 1.26.1
  YQ_VERSION: 4.43.1

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Get Latest argo-cd version
        id: get-argocd-version
        run: |
          version=$(curl -L https://api.github.com/repos/argoproj/argo-cd/releases | jq  -r '.[]|select((.tag_name|contains("-rc")|not)).tag_name' | sort -V | tail -1)
          echo "ARGOCD_VERSION=${version}" >> $GITHUB_OUTPUT

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          build-args: |
            ARGOCD_VERSION=${{ steps.get-argocd-version.outputs.ARGOCD_VERSION }}
            SOPS_VERSION=${{ env.SOPS_VERSION }}
            VALS_VERSION=${{ env.VALS_VERSION }}
            HELM_SECRETS_VERSION=${{ env.HELM_SECRETS_VERSION }}
            HELMFILE_VERSION=${{ env.HELMFILE_VERSION }}
            HELM_GIT_VERSION=${{ env.HELM_GIT_VERSION }}
            KUBECTL_VERSION=${{ env.KUBECTL_VERSION }}
            YQ_VERSION=${{ env.YQ_VERSION }}
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ steps.get-argocd-version.outputs.ARGOCD_VERSION }}-${{ env.HELM_SECRETS_VERSION }}

      - name: Push docker image
        uses: docker/build-push-action@v5
        if: github.ref_name == 'main'
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            ARGOCD_VERSION=${{ steps.get-argocd-version.outputs.ARGOCD_VERSION }}
            SOPS_VERSION=${{ env.SOPS_VERSION }}
            VALS_VERSION=${{ env.VALS_VERSION }}
            HELM_SECRETS_VERSION=${{ env.HELM_SECRETS_VERSION }}
            HELMFILE_VERSION=${{ env.HELMFILE_VERSION }}
            HELM_GIT_VERSION=${{ env.HELM_GIT_VERSION }}
            KUBECTL_VERSION=${{ env.KUBECTL_VERSION }}
            YQ_VERSION=${{ env.YQ_VERSION }}
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ steps.get-argocd-version.outputs.ARGOCD_VERSION }}-${{ env.HELM_SECRETS_VERSION }}
