name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

env:
  ARGOCD_VERSION: v2.7.1
  SOPS_VERSION: 3.7.3
  VALS_VERSION: 0.22.0
  HELM_SECRETS_VERSION: 4.4.2
  KUBECTL_VERSION: 1.26.1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: false
          build-args: |
            ARGOCD_VERSION=${{ env.ARGOCD_VERSION }}
            SOPS_VERSION=${{ env.SOPS_VERSION }}
            VALS_VERSION=${{ env.VALS_VERSION }}
            HELM_SECRETS_VERSION=${{ env.HELM_SECRETS_VERSION }}
            KUBECTL_VERSION=${{ env.KUBECTL_VERSION }}
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ env.ARGOCD_VERSION }}-${{ env.HELM_SECRETS_VERSION }}

      - name: Push docker image
        uses: docker/build-push-action@v3
        if: github.ref_name == 'main'
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            ARGOCD_VERSION=${{ env.ARGOCD_VERSION }}
            SOPS_VERSION=${{ env.SOPS_VERSION }}
            VALS_VERSION=${{ env.VALS_VERSION }}
            HELM_SECRETS_VERSION=${{ env.HELM_SECRETS_VERSION }}
            KUBECTL_VERSION=${{ env.KUBECTL_VERSION }}
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ env.ARGOCD_VERSION }}-${{ env.HELM_SECRETS_VERSION }}
